//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", ConfigurationName="TermService.TermWebService")]
    public interface TermWebService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="IllegalParametersFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermOptionsAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmTermBaseResponseAPI))]
        System.Threading.Tasks.Task<TermService.exportTermResponse> exportTermAsync(TermService.exportTerm request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="IllegalParametersFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermOptionsAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmTermBaseResponseAPI))]
        System.Threading.Tasks.Task<TermService.checkTermCompletionResponse> checkTermCompletionAsync(TermService.checkTermCompletion request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="IllegalParametersFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermOptionsAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmTermBaseResponseAPI))]
        System.Threading.Tasks.Task<TermService.downloadTermMTOMResponse> downloadTermMTOMAsync(TermService.downloadTermMTOM request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="IllegalParametersFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermOptionsAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmTermBaseResponseAPI))]
        System.Threading.Tasks.Task<TermService.importTermMTOMResponse> importTermMTOMAsync(TermService.importTermMTOM request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="IllegalParametersFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermOptionsAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmTermBaseResponseAPI))]
        System.Threading.Tasks.Task<TermService.downloadTermURLResponse> downloadTermURLAsync(TermService.downloadTermURL request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="IllegalParametersFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="AuthenticationFault")]
        [System.ServiceModel.FaultContractAttribute(typeof(string), Action="", Name="ProcessingFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermOptionsAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmImportTermAPI))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(xtmTermBaseResponseAPI))]
        System.Threading.Tasks.Task<TermService.importTermURLResponse> importTermURLAsync(TermService.importTermURL request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class loginAPI
    {
        
        private string clientField;
        
        private string integrationKeyField;
        
        private languageCODE languageField;
        
        private bool languageFieldSpecified;
        
        private string passwordField;
        
        private long userIdField;
        
        private bool userIdFieldSpecified;
        
        private string usernameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string client
        {
            get
            {
                return this.clientField;
            }
            set
            {
                this.clientField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string integrationKey
        {
            get
            {
                return this.integrationKeyField;
            }
            set
            {
                this.integrationKeyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public languageCODE language
        {
            get
            {
                return this.languageField;
            }
            set
            {
                this.languageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool languageSpecified
        {
            get
            {
                return this.languageFieldSpecified;
            }
            set
            {
                this.languageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public long userId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool userIdSpecified
        {
            get
            {
                return this.userIdFieldSpecified;
            }
            set
            {
                this.userIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public enum languageCODE
    {
        
        /// <remarks/>
        ab,
        
        /// <remarks/>
        aa_ET,
        
        /// <remarks/>
        ak,
        
        /// <remarks/>
        af_ZA,
        
        /// <remarks/>
        sq_AL,
        
        /// <remarks/>
        am_ET,
        
        /// <remarks/>
        am_ER,
        
        /// <remarks/>
        ar_AA,
        
        /// <remarks/>
        ar_AE,
        
        /// <remarks/>
        ar_BH,
        
        /// <remarks/>
        ar_DZ,
        
        /// <remarks/>
        ar_EG,
        
        /// <remarks/>
        ar_EH,
        
        /// <remarks/>
        ar_IQ,
        
        /// <remarks/>
        ar_JO,
        
        /// <remarks/>
        ar_KW,
        
        /// <remarks/>
        ar_LB,
        
        /// <remarks/>
        ar_LY,
        
        /// <remarks/>
        ar_MA,
        
        /// <remarks/>
        ar_MR,
        
        /// <remarks/>
        ar_OM,
        
        /// <remarks/>
        ar_PS,
        
        /// <remarks/>
        ar_QA,
        
        /// <remarks/>
        ar_SA,
        
        /// <remarks/>
        ar_SD,
        
        /// <remarks/>
        ar_SY,
        
        /// <remarks/>
        ar_TD,
        
        /// <remarks/>
        ar_TN,
        
        /// <remarks/>
        ar_YE,
        
        /// <remarks/>
        hy_AM,
        
        /// <remarks/>
        hy_AM_arevela,
        
        /// <remarks/>
        hy_AM_arevmda,
        
        /// <remarks/>
        as_IN,
        
        /// <remarks/>
        ast_ES,
        
        /// <remarks/>
        ay_BO,
        
        /// <remarks/>
        az_AZ_Cyrl,
        
        /// <remarks/>
        az_AZ_Latn,
        
        /// <remarks/>
        ba_RU,
        
        /// <remarks/>
        bal_IR,
        
        /// <remarks/>
        bh_IN,
        
        /// <remarks/>
        bi_VU,
        
        /// <remarks/>
        bs_BA_Cyrl,
        
        /// <remarks/>
        bs_BA_Latn,
        
        /// <remarks/>
        br_FR,
        
        /// <remarks/>
        bsk,
        
        /// <remarks/>
        my_MM,
        
        /// <remarks/>
        be_BY,
        
        /// <remarks/>
        cal,
        
        /// <remarks/>
        ca_ES,
        
        /// <remarks/>
        ceb,
        
        /// <remarks/>
        cha,
        
        /// <remarks/>
        ny_MW,
        
        /// <remarks/>
        zh_CN,
        
        /// <remarks/>
        zh_TW,
        
        /// <remarks/>
        zh_HK,
        
        /// <remarks/>
        zh_SG,
        
        /// <remarks/>
        chk,
        
        /// <remarks/>
        co_FR,
        
        /// <remarks/>
        hr_HR,
        
        /// <remarks/>
        cs_CZ,
        
        /// <remarks/>
        eu_ES,
        
        /// <remarks/>
        bn_IN,
        
        /// <remarks/>
        bn_BD,
        
        /// <remarks/>
        bg_BG,
        
        /// <remarks/>
        ca_AD,
        
        /// <remarks/>
        dnj,
        
        /// <remarks/>
        da_DK,
        
        /// <remarks/>
        prs_AF,
        
        /// <remarks/>
        dv_IN,
        
        /// <remarks/>
        mis,
        
        /// <remarks/>
        nl_NL,
        
        /// <remarks/>
        en_US,
        
        /// <remarks/>
        en_GB,
        
        /// <remarks/>
        en_142,
        
        /// <remarks/>
        en_CA,
        
        /// <remarks/>
        en_AU,
        
        /// <remarks/>
        en_NZ,
        
        /// <remarks/>
        en_ZA,
        
        /// <remarks/>
        en_CH,
        
        /// <remarks/>
        en_HK,
        
        /// <remarks/>
        en_IN,
        
        /// <remarks/>
        en_IE,
        
        /// <remarks/>
        en_SG,
        
        /// <remarks/>
        en_AE,
        
        /// <remarks/>
        en_DE,
        
        /// <remarks/>
        en_NL,
        
        /// <remarks/>
        en_AT,
        
        /// <remarks/>
        en_NT,
        
        /// <remarks/>
        en_CY,
        
        /// <remarks/>
        en_KE,
        
        /// <remarks/>
        en_BS,
        
        /// <remarks/>
        en_MY,
        
        /// <remarks/>
        en_PK,
        
        /// <remarks/>
        eo,
        
        /// <remarks/>
        et_EE,
        
        /// <remarks/>
        ee_GH,
        
        /// <remarks/>
        fo_FO,
        
        /// <remarks/>
        fj_FJ,
        
        /// <remarks/>
        fil_PH,
        
        /// <remarks/>
        fi_FI,
        
        /// <remarks/>
        nl_BE,
        
        /// <remarks/>
        fr_FR,
        
        /// <remarks/>
        fr_CA,
        
        /// <remarks/>
        fr_CH,
        
        /// <remarks/>
        fr_BE,
        
        /// <remarks/>
        fr_LU,
        
        /// <remarks/>
        fr_MA,
        
        /// <remarks/>
        fr_SN,
        
        /// <remarks/>
        fy,
        
        /// <remarks/>
        fu,
        
        /// <remarks/>
        fat,
        
        /// <remarks/>
        gl_ES,
        
        /// <remarks/>
        ka_GE,
        
        /// <remarks/>
        kar,
        
        /// <remarks/>
        de_DE,
        
        /// <remarks/>
        de_AT,
        
        /// <remarks/>
        de_BE,
        
        /// <remarks/>
        de_CH,
        
        /// <remarks/>
        de_LU,
        
        /// <remarks/>
        de_NL,
        
        /// <remarks/>
        lb_LU,
        
        /// <remarks/>
        kl_GL,
        
        /// <remarks/>
        el_GR,
        
        /// <remarks/>
        el_CY,
        
        /// <remarks/>
        grc_GR,
        
        /// <remarks/>
        grn,
        
        /// <remarks/>
        gu_IN,
        
        /// <remarks/>
        ht_HT,
        
        /// <remarks/>
        cnh,
        
        /// <remarks/>
        ha_NG,
        
        /// <remarks/>
        he_IL,
        
        /// <remarks/>
        hi_IN,
        
        /// <remarks/>
        hil,
        
        /// <remarks/>
        hmn,
        
        /// <remarks/>
        hmn_US,
        
        /// <remarks/>
        hu_HU,
        
        /// <remarks/>
        haw,
        
        /// <remarks/>
        is_IS,
        
        /// <remarks/>
        ig,
        
        /// <remarks/>
        ilo,
        
        /// <remarks/>
        id_ID,
        
        /// <remarks/>
        ia,
        
        /// <remarks/>
        ie,
        
        /// <remarks/>
        iu,
        
        /// <remarks/>
        ium,
        
        /// <remarks/>
        ik,
        
        /// <remarks/>
        ga_IE,
        
        /// <remarks/>
        it_IT,
        
        /// <remarks/>
        it_CH,
        
        /// <remarks/>
        ja_JP,
        
        /// <remarks/>
        jv_ID,
        
        /// <remarks/>
        ks,
        
        /// <remarks/>
        kk_KZ,
        
        /// <remarks/>
        kg_CG,
        
        /// <remarks/>
        rw_RW,
        
        /// <remarks/>
        ky,
        
        /// <remarks/>
        rn,
        
        /// <remarks/>
        sw_KE,
        
        /// <remarks/>
        km_KH,
        
        /// <remarks/>
        kn_IN,
        
        /// <remarks/>
        kok_IN,
        
        /// <remarks/>
        tlh,
        
        /// <remarks/>
        ko_KR,
        
        /// <remarks/>
        kos,
        
        /// <remarks/>
        ku_TR,
        
        /// <remarks/>
        kmr,
        
        /// <remarks/>
        ckb,
        
        /// <remarks/>
        ku_IQ,
        
        /// <remarks/>
        lo_LA,
        
        /// <remarks/>
        la,
        
        /// <remarks/>
        lv_LV,
        
        /// <remarks/>
        ln_CG,
        
        /// <remarks/>
        lt_LT,
        
        /// <remarks/>
        mfe_MU,
        
        /// <remarks/>
        mk_MK,
        
        /// <remarks/>
        mg_MG,
        
        /// <remarks/>
        ms_MY,
        
        /// <remarks/>
        ms_SG,
        
        /// <remarks/>
        ml_IN,
        
        /// <remarks/>
        mt_MT,
        
        /// <remarks/>
        mi_NZ,
        
        /// <remarks/>
        mr_IN,
        
        /// <remarks/>
        mah,
        
        /// <remarks/>
        mn_MN,
        
        /// <remarks/>
        sla_ME,
        
        /// <remarks/>
        mo_MD,
        
        /// <remarks/>
        na_NR,
        
        /// <remarks/>
        nv,
        
        /// <remarks/>
        nd_ZW,
        
        /// <remarks/>
        ne_NP,
        
        /// <remarks/>
        no_NO,
        
        /// <remarks/>
        nb_NO,
        
        /// <remarks/>
        nn_NO,
        
        /// <remarks/>
        nso_ZA,
        
        /// <remarks/>
        nus,
        
        /// <remarks/>
        oc_FR,
        
        /// <remarks/>
        or_IN,
        
        /// <remarks/>
        om_ET,
        
        /// <remarks/>
        ota,
        
        /// <remarks/>
        pau,
        
        /// <remarks/>
        ps,
        
        /// <remarks/>
        ps_PK,
        
        /// <remarks/>
        fa_IR,
        
        /// <remarks/>
        pon,
        
        /// <remarks/>
        pl_PL,
        
        /// <remarks/>
        pt_PT,
        
        /// <remarks/>
        pt_BR,
        
        /// <remarks/>
        pt_MZ,
        
        /// <remarks/>
        pt_AO,
        
        /// <remarks/>
        pa_PA,
        
        /// <remarks/>
        pa_IN,
        
        /// <remarks/>
        pa_PK,
        
        /// <remarks/>
        qu_PE,
        
        /// <remarks/>
        qya,
        
        /// <remarks/>
        xr_MM,
        
        /// <remarks/>
        rm_CH,
        
        /// <remarks/>
        ro_RO,
        
        /// <remarks/>
        ro_MD,
        
        /// <remarks/>
        ru_RU,
        
        /// <remarks/>
        ru_AM,
        
        /// <remarks/>
        ru_AZ,
        
        /// <remarks/>
        ru_GE,
        
        /// <remarks/>
        ru_MD,
        
        /// <remarks/>
        ru_UA,
        
        /// <remarks/>
        sm_WS,
        
        /// <remarks/>
        sg,
        
        /// <remarks/>
        sa_IN,
        
        /// <remarks/>
        sc_IT,
        
        /// <remarks/>
        gd_GB,
        
        /// <remarks/>
        st,
        
        /// <remarks/>
        tn_ZA,
        
        /// <remarks/>
        sr_YU,
        
        /// <remarks/>
        sr_RS_Cyrl,
        
        /// <remarks/>
        sr_ME_Cyrl,
        
        /// <remarks/>
        sr_ME_Latn,
        
        /// <remarks/>
        sr_RS_Latn,
        
        /// <remarks/>
        sn,
        
        /// <remarks/>
        sjn,
        
        /// <remarks/>
        sd_PK,
        
        /// <remarks/>
        si_LK,
        
        /// <remarks/>
        ss,
        
        /// <remarks/>
        sk_SK,
        
        /// <remarks/>
        sl_SI,
        
        /// <remarks/>
        so_SO,
        
        /// <remarks/>
        dsb_DE,
        
        /// <remarks/>
        hsb_DE,
        
        /// <remarks/>
        es_ES,
        
        /// <remarks/>
        es_AR,
        
        /// <remarks/>
        es_BO,
        
        /// <remarks/>
        es_CL,
        
        /// <remarks/>
        es_CO,
        
        /// <remarks/>
        es_CR,
        
        /// <remarks/>
        es_CU,
        
        /// <remarks/>
        es_DO,
        
        /// <remarks/>
        es_EC,
        
        /// <remarks/>
        es_SV,
        
        /// <remarks/>
        es_GT,
        
        /// <remarks/>
        es_HN,
        
        /// <remarks/>
        es_419,
        
        /// <remarks/>
        es_MX,
        
        /// <remarks/>
        es_NI,
        
        /// <remarks/>
        es_PA,
        
        /// <remarks/>
        es_PY,
        
        /// <remarks/>
        es_PE,
        
        /// <remarks/>
        es_PR,
        
        /// <remarks/>
        es_UY,
        
        /// <remarks/>
        es_US,
        
        /// <remarks/>
        es_VE,
        
        /// <remarks/>
        es_001,
        
        /// <remarks/>
        es_NT,
        
        /// <remarks/>
        sw_SO,
        
        /// <remarks/>
        sw_TZ,
        
        /// <remarks/>
        sw_UG,
        
        /// <remarks/>
        sv_SE,
        
        /// <remarks/>
        sv_FI,
        
        /// <remarks/>
        apd_SD,
        
        /// <remarks/>
        apd_SD_Latn,
        
        /// <remarks/>
        sun,
        
        /// <remarks/>
        syr_TR,
        
        /// <remarks/>
        tl_PH,
        
        /// <remarks/>
        tg_TJ,
        
        /// <remarks/>
        ta_IN,
        
        /// <remarks/>
        ta_SG,
        
        /// <remarks/>
        ta_LK,
        
        /// <remarks/>
        tt_RU,
        
        /// <remarks/>
        te_IN,
        
        /// <remarks/>
        tet_ID,
        
        /// <remarks/>
        tet_TL,
        
        /// <remarks/>
        th_TH,
        
        /// <remarks/>
        bo,
        
        /// <remarks/>
        ti,
        
        /// <remarks/>
        to_TO,
        
        /// <remarks/>
        ts_ZA,
        
        /// <remarks/>
        tn_BW,
        
        /// <remarks/>
        tr_TR,
        
        /// <remarks/>
        tk_TM,
        
        /// <remarks/>
        tw,
        
        /// <remarks/>
        uk_UA,
        
        /// <remarks/>
        ur_IN,
        
        /// <remarks/>
        ur_PK,
        
        /// <remarks/>
        ug_CN,
        
        /// <remarks/>
        uz_UZ_Cyrl,
        
        /// <remarks/>
        uz_UZ_Latn,
        
        /// <remarks/>
        uz_AF,
        
        /// <remarks/>
        cy_GB,
        
        /// <remarks/>
        vi_VN,
        
        /// <remarks/>
        vo,
        
        /// <remarks/>
        wo,
        
        /// <remarks/>
        xh_ZA,
        
        /// <remarks/>
        xz_AF,
        
        /// <remarks/>
        yap,
        
        /// <remarks/>
        yi,
        
        /// <remarks/>
        yi_IL,
        
        /// <remarks/>
        yi_US,
        
        /// <remarks/>
        yo_NG,
        
        /// <remarks/>
        czt,
        
        /// <remarks/>
        zu_ZA,
        
        /// <remarks/>
        kun,
        
        /// <remarks/>
        lua,
        
        /// <remarks/>
        sco_GB,
        
        /// <remarks/>
        sco_IE,
        
        /// <remarks/>
        fr_CG,
        
        /// <remarks/>
        zh_YUE,
        
        /// <remarks/>
        lug,
        
        /// <remarks/>
        ogo,
        
        /// <remarks/>
        bbc,
        
        /// <remarks/>
        ksw,
        
        /// <remarks/>
        cfm,
        
        /// <remarks/>
        cmn,
        
        /// <remarks/>
        goyu,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmDownloadTermURLOptionsAPI
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmImportTermURLOptionsAPI))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmImportTermMTOMOptionsAPI))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmImportTermOptionsAPI
    {
        
        private bool addToExistingTermsField;
        
        private bool addToExistingTermsFieldSpecified;
        
        private bool purgeTermsField;
        
        private bool purgeTermsFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool addToExistingTerms
        {
            get
            {
                return this.addToExistingTermsField;
            }
            set
            {
                this.addToExistingTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool addToExistingTermsSpecified
        {
            get
            {
                return this.addToExistingTermsFieldSpecified;
            }
            set
            {
                this.addToExistingTermsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool purgeTerms
        {
            get
            {
                return this.purgeTermsField;
            }
            set
            {
                this.purgeTermsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool purgeTermsSpecified
        {
            get
            {
                return this.purgeTermsFieldSpecified;
            }
            set
            {
                this.purgeTermsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmImportTermURLOptionsAPI : xtmImportTermOptionsAPI
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmImportTermMTOMOptionsAPI : xtmImportTermOptionsAPI
    {
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmImportTermURLAPI))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmImportTermMTOMAPI))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmImportTermAPI
    {
        
        private xtmCustomerDescriptorAPI customerField;
        
        private xtmTermFileTypeEnum fileTypeField;
        
        private bool fileTypeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public xtmCustomerDescriptorAPI customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public xtmTermFileTypeEnum fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileTypeSpecified
        {
            get
            {
                return this.fileTypeFieldSpecified;
            }
            set
            {
                this.fileTypeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmCustomerDescriptorAPI
    {
        
        private long externalIdField;
        
        private bool externalIdFieldSpecified;
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long externalId
        {
            get
            {
                return this.externalIdField;
            }
            set
            {
                this.externalIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool externalIdSpecified
        {
            get
            {
                return this.externalIdFieldSpecified;
            }
            set
            {
                this.externalIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public enum xtmTermFileTypeEnum
    {
        
        /// <remarks/>
        TBX,
        
        /// <remarks/>
        MTF,
        
        /// <remarks/>
        XLS,
        
        /// <remarks/>
        XLSX,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmImportTermURLAPI : xtmImportTermAPI
    {
        
        private string urlField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string url
        {
            get
            {
                return this.urlField;
            }
            set
            {
                this.urlField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmImportTermMTOMAPI : xtmImportTermAPI
    {
        
        private byte[] fileMTOMField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] fileMTOM
        {
            get
            {
                return this.fileMTOMField;
            }
            set
            {
                this.fileMTOMField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmTermURLResponseAPI))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmTermMTOMResponseAPI))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermBaseResponseAPI
    {
        
        private xtmTermBaseFileDescriptorAPI fileField;
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public xtmTermBaseFileDescriptorAPI file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(xtmTermFileDescriptorAPI))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermBaseFileDescriptorAPI
    {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified
        {
            get
            {
                return this.idFieldSpecified;
            }
            set
            {
                this.idFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermFileDescriptorAPI : xtmTermBaseFileDescriptorAPI
    {
        
        private string fileNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string fileName
        {
            get
            {
                return this.fileNameField;
            }
            set
            {
                this.fileNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermURLResponseAPI : xtmTermBaseResponseAPI
    {
        
        private string fileURLField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="anyURI", Order=0)]
        public string fileURL
        {
            get
            {
                return this.fileURLField;
            }
            set
            {
                this.fileURLField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermMTOMResponseAPI : xtmTermBaseResponseAPI
    {
        
        private byte[] fileMTOMField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=0)]
        public byte[] fileMTOM
        {
            get
            {
                return this.fileMTOMField;
            }
            set
            {
                this.fileMTOMField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmDownloadTermMTOMOptionsAPI
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermStatusResponseAPI
    {
        
        private xtmTermFileDescriptorAPI fileField;
        
        private xtmTermCompletionStatusEnum statusField;
        
        private bool statusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public xtmTermFileDescriptorAPI file
        {
            get
            {
                return this.fileField;
            }
            set
            {
                this.fileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public xtmTermCompletionStatusEnum status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public enum xtmTermCompletionStatusEnum
    {
        
        /// <remarks/>
        IN_PROGRESS,
        
        /// <remarks/>
        FINISHED,
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        NOT_EXIST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmCheckTermCompletionOptionsAPI
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmExportTermOptionsAPI
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmTermDomainAPI
    {
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public partial class xtmExportTermAPI
    {
        
        private bool allLanguagesField;
        
        private bool allLanguagesFieldSpecified;
        
        private System.Nullable<xtmTermColumnsEnum>[] columnsToExportField;
        
        private xtmCustomerDescriptorAPI customerField;
        
        private xtmTermDomainAPI domainField;
        
        private xtmTermFileTypeEnum fileTypeField;
        
        private bool fileTypeFieldSpecified;
        
        private languageCODE mainLanguageField;
        
        private bool mainLanguageFieldSpecified;
        
        private xtmTermStatusEnum statusField;
        
        private bool statusFieldSpecified;
        
        private System.Nullable<languageCODE>[] translationLanguagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool allLanguages
        {
            get
            {
                return this.allLanguagesField;
            }
            set
            {
                this.allLanguagesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool allLanguagesSpecified
        {
            get
            {
                return this.allLanguagesFieldSpecified;
            }
            set
            {
                this.allLanguagesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("columnsToExport", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public System.Nullable<xtmTermColumnsEnum>[] columnsToExport
        {
            get
            {
                return this.columnsToExportField;
            }
            set
            {
                this.columnsToExportField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public xtmCustomerDescriptorAPI customer
        {
            get
            {
                return this.customerField;
            }
            set
            {
                this.customerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public xtmTermDomainAPI domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public xtmTermFileTypeEnum fileType
        {
            get
            {
                return this.fileTypeField;
            }
            set
            {
                this.fileTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fileTypeSpecified
        {
            get
            {
                return this.fileTypeFieldSpecified;
            }
            set
            {
                this.fileTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public languageCODE mainLanguage
        {
            get
            {
                return this.mainLanguageField;
            }
            set
            {
                this.mainLanguageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool mainLanguageSpecified
        {
            get
            {
                return this.mainLanguageFieldSpecified;
            }
            set
            {
                this.mainLanguageFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public xtmTermStatusEnum status
        {
            get
            {
                return this.statusField;
            }
            set
            {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool statusSpecified
        {
            get
            {
                return this.statusFieldSpecified;
            }
            set
            {
                this.statusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("translationLanguages", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=7)]
        public System.Nullable<languageCODE>[] translationLanguages
        {
            get
            {
                return this.translationLanguagesField;
            }
            set
            {
                this.translationLanguagesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public enum xtmTermColumnsEnum
    {
        
        /// <remarks/>
        ABBREVIATION,
        
        /// <remarks/>
        CONTEXT,
        
        /// <remarks/>
        DOMAIN,
        
        /// <remarks/>
        LAST_MOD_DATE,
        
        /// <remarks/>
        REFERENCE,
        
        /// <remarks/>
        REMARKS,
        
        /// <remarks/>
        DEFINITION,
        
        /// <remarks/>
        LAST_MOD_BY,
        
        /// <remarks/>
        STATUS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/")]
    public enum xtmTermStatusEnum
    {
        
        /// <remarks/>
        ALL,
        
        /// <remarks/>
        VALID,
        
        /// <remarks/>
        NOT_APPROVED,
        
        /// <remarks/>
        REJECTED,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportTerm", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class exportTerm
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.loginAPI loginAPI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmExportTermAPI[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmExportTermOptionsAPI options;
        
        public exportTerm()
        {
        }
        
        public exportTerm(TermService.loginAPI loginAPI, TermService.xtmExportTermAPI[] files, TermService.xtmExportTermOptionsAPI options)
        {
            this.loginAPI = loginAPI;
            this.files = files;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="exportTermResponse", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class exportTermResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermFileDescriptorAPI[] @return;
        
        public exportTermResponse()
        {
        }
        
        public exportTermResponse(TermService.xtmTermFileDescriptorAPI[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkTermCompletion", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class checkTermCompletion
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.loginAPI loginAPI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermBaseFileDescriptorAPI[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmCheckTermCompletionOptionsAPI options;
        
        public checkTermCompletion()
        {
        }
        
        public checkTermCompletion(TermService.loginAPI loginAPI, TermService.xtmTermBaseFileDescriptorAPI[] files, TermService.xtmCheckTermCompletionOptionsAPI options)
        {
            this.loginAPI = loginAPI;
            this.files = files;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkTermCompletionResponse", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class checkTermCompletionResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermStatusResponseAPI[] @return;
        
        public checkTermCompletionResponse()
        {
        }
        
        public checkTermCompletionResponse(TermService.xtmTermStatusResponseAPI[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadTermMTOM", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class downloadTermMTOM
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.loginAPI loginAPI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermBaseFileDescriptorAPI[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmDownloadTermMTOMOptionsAPI options;
        
        public downloadTermMTOM()
        {
        }
        
        public downloadTermMTOM(TermService.loginAPI loginAPI, TermService.xtmTermBaseFileDescriptorAPI[] files, TermService.xtmDownloadTermMTOMOptionsAPI options)
        {
            this.loginAPI = loginAPI;
            this.files = files;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadTermMTOMResponse", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class downloadTermMTOMResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermMTOMResponseAPI[] @return;
        
        public downloadTermMTOMResponse()
        {
        }
        
        public downloadTermMTOMResponse(TermService.xtmTermMTOMResponseAPI[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importTermMTOM", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class importTermMTOM
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.loginAPI loginAPI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmImportTermMTOMAPI[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmImportTermMTOMOptionsAPI options;
        
        public importTermMTOM()
        {
        }
        
        public importTermMTOM(TermService.loginAPI loginAPI, TermService.xtmImportTermMTOMAPI[] files, TermService.xtmImportTermMTOMOptionsAPI options)
        {
            this.loginAPI = loginAPI;
            this.files = files;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importTermMTOMResponse", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class importTermMTOMResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("termFiles", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermFileDescriptorAPI[] @return;
        
        public importTermMTOMResponse()
        {
        }
        
        public importTermMTOMResponse(TermService.xtmTermFileDescriptorAPI[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadTermURL", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class downloadTermURL
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.loginAPI loginAPI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermBaseFileDescriptorAPI[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmDownloadTermURLOptionsAPI options;
        
        public downloadTermURL()
        {
        }
        
        public downloadTermURL(TermService.loginAPI loginAPI, TermService.xtmTermBaseFileDescriptorAPI[] files, TermService.xtmDownloadTermURLOptionsAPI options)
        {
            this.loginAPI = loginAPI;
            this.files = files;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="downloadTermURLResponse", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class downloadTermURLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermURLResponseAPI[] @return;
        
        public downloadTermURLResponse()
        {
        }
        
        public downloadTermURLResponse(TermService.xtmTermURLResponseAPI[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importTermURL", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class importTermURL
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.loginAPI loginAPI;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmImportTermURLAPI[] files;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmImportTermURLOptionsAPI options;
        
        public importTermURL()
        {
        }
        
        public importTermURL(TermService.loginAPI loginAPI, TermService.xtmImportTermURLAPI[] files, TermService.xtmImportTermURLOptionsAPI options)
        {
            this.loginAPI = loginAPI;
            this.files = files;
            this.options = options;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="importTermURLResponse", WrapperNamespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", IsWrapped=true)]
    public partial class importTermURLResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://term.v2.webservice.projectmanagergui.xmlintl.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("files", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TermService.xtmTermFileDescriptorAPI[] @return;
        
        public importTermURLResponse()
        {
        }
        
        public importTermURLResponse(TermService.xtmTermFileDescriptorAPI[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface TermWebServiceChannel : TermService.TermWebService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class TermWebServiceClient : System.ServiceModel.ClientBase<TermService.TermWebService>, TermService.TermWebService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TermWebServiceClient() : 
                base(TermWebServiceClient.GetDefaultBinding(), TermWebServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.XTMTermWebServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TermWebServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(TermWebServiceClient.GetBindingForEndpoint(endpointConfiguration), TermWebServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TermWebServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TermWebServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TermWebServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TermWebServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TermWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TermService.exportTermResponse> TermService.TermWebService.exportTermAsync(TermService.exportTerm request)
        {
            return base.Channel.exportTermAsync(request);
        }
        
        public System.Threading.Tasks.Task<TermService.exportTermResponse> exportTermAsync(TermService.loginAPI loginAPI, TermService.xtmExportTermAPI[] files, TermService.xtmExportTermOptionsAPI options)
        {
            TermService.exportTerm inValue = new TermService.exportTerm();
            inValue.loginAPI = loginAPI;
            inValue.files = files;
            inValue.options = options;
            return ((TermService.TermWebService)(this)).exportTermAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TermService.checkTermCompletionResponse> TermService.TermWebService.checkTermCompletionAsync(TermService.checkTermCompletion request)
        {
            return base.Channel.checkTermCompletionAsync(request);
        }
        
        public System.Threading.Tasks.Task<TermService.checkTermCompletionResponse> checkTermCompletionAsync(TermService.loginAPI loginAPI, TermService.xtmTermBaseFileDescriptorAPI[] files, TermService.xtmCheckTermCompletionOptionsAPI options)
        {
            TermService.checkTermCompletion inValue = new TermService.checkTermCompletion();
            inValue.loginAPI = loginAPI;
            inValue.files = files;
            inValue.options = options;
            return ((TermService.TermWebService)(this)).checkTermCompletionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TermService.downloadTermMTOMResponse> TermService.TermWebService.downloadTermMTOMAsync(TermService.downloadTermMTOM request)
        {
            return base.Channel.downloadTermMTOMAsync(request);
        }
        
        public System.Threading.Tasks.Task<TermService.downloadTermMTOMResponse> downloadTermMTOMAsync(TermService.loginAPI loginAPI, TermService.xtmTermBaseFileDescriptorAPI[] files, TermService.xtmDownloadTermMTOMOptionsAPI options)
        {
            TermService.downloadTermMTOM inValue = new TermService.downloadTermMTOM();
            inValue.loginAPI = loginAPI;
            inValue.files = files;
            inValue.options = options;
            return ((TermService.TermWebService)(this)).downloadTermMTOMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TermService.importTermMTOMResponse> TermService.TermWebService.importTermMTOMAsync(TermService.importTermMTOM request)
        {
            return base.Channel.importTermMTOMAsync(request);
        }
        
        public System.Threading.Tasks.Task<TermService.importTermMTOMResponse> importTermMTOMAsync(TermService.loginAPI loginAPI, TermService.xtmImportTermMTOMAPI[] files, TermService.xtmImportTermMTOMOptionsAPI options)
        {
            TermService.importTermMTOM inValue = new TermService.importTermMTOM();
            inValue.loginAPI = loginAPI;
            inValue.files = files;
            inValue.options = options;
            return ((TermService.TermWebService)(this)).importTermMTOMAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TermService.downloadTermURLResponse> TermService.TermWebService.downloadTermURLAsync(TermService.downloadTermURL request)
        {
            return base.Channel.downloadTermURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TermService.downloadTermURLResponse> downloadTermURLAsync(TermService.loginAPI loginAPI, TermService.xtmTermBaseFileDescriptorAPI[] files, TermService.xtmDownloadTermURLOptionsAPI options)
        {
            TermService.downloadTermURL inValue = new TermService.downloadTermURL();
            inValue.loginAPI = loginAPI;
            inValue.files = files;
            inValue.options = options;
            return ((TermService.TermWebService)(this)).downloadTermURLAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TermService.importTermURLResponse> TermService.TermWebService.importTermURLAsync(TermService.importTermURL request)
        {
            return base.Channel.importTermURLAsync(request);
        }
        
        public System.Threading.Tasks.Task<TermService.importTermURLResponse> importTermURLAsync(TermService.loginAPI loginAPI, TermService.xtmImportTermURLAPI[] files, TermService.xtmImportTermURLOptionsAPI options)
        {
            TermService.importTermURL inValue = new TermService.importTermURL();
            inValue.loginAPI = loginAPI;
            inValue.files = files;
            inValue.options = options;
            return ((TermService.TermWebService)(this)).importTermURLAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XTMTermWebServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.XTMTermWebServicePort))
            {
                return new System.ServiceModel.EndpointAddress("https://x106.xtm-intl.com/project-manager-gui/services/v2/term/XTMTermWebService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return TermWebServiceClient.GetBindingForEndpoint(EndpointConfiguration.XTMTermWebServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return TermWebServiceClient.GetEndpointAddress(EndpointConfiguration.XTMTermWebServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            XTMTermWebServicePort,
        }
    }
}
